name: Add Project
on:
  workflow_dispatch:
    inputs:
      index:
        description: 'Index Number'
        required: true
      repo_name:
        description: 'Repository Name (user/repo)'
        required: true
      api_name:
        description: 'API Name'
        required: true
concurrency:
    group: add-project
    cancel-in-progress: false
jobs:
  version-bump:
    name: Add Project
    runs-on: ubuntu-latest
    steps:
       - name: Fetch Homepage URL using Github API
         id: apidata
         uses: fjogeleit/http-request-action@master
         with:
           url: "https://api.github.com/repos/${{ github.event.inputs.repo_name }}"
           method: GET
       - name: Checkout Source
         uses: actions/checkout@v2
       - name: Add project as submodule
         run: |
            git config pull.rebase true || true
            git pull || true
            git submodule add https://github.com/${{ github.event.inputs.repo_name }} "${{ github.event.inputs.index }}-${{ github.event.inputs.api_name }}-API"
       - name: Add URL to README
         run: |
            echo "API Data -------------- ${{ steps.apidata.outputs.response.homepage }} ------------------- ${{ steps.apidata.outputs.response }}"
            printf "\n${{ github.event.inputs.index }}. [${{ github.event.inputs.api_name }} API](${{ steps.apidata.outputs.response.homepage }})" >> README.md
       - name: Commit changes
         run: |
            git config user.name nikiljos-bot
            git config user.email bot@nikjos.in
            git add --all || true
            git commit -m "Added ${{ github.event.inputs.api_name }}" || true
            git push --quiet
